const openRouter = require('./openrouter');
const genesis = require('./genesis'); // Reuse safeParse

class GapAgent {
    /**
     * Analyze the current context and identify missing information.
     */
    async analyze(contextText, fileNames = []) {
        // Short-circuit if context is empty to prevent AI hallucinations (e.g. "UrbanNest")
        if (!contextText || contextText.trim().length < 10) {
            return {
                completenessScore: 0,
                missingDimensions: ["Business Context", "Target Audience", "Value Proposition", "Competitors", "Goals"],
                recommendations: [
                    "Start by entering your business context in the settings.",
                    "Upload any existing strategy documents or pitch decks."
                ],
                summary: "No knowledge base detected. Please provide context to get started."
            };
        }

        const prompt = `
            You are an expert Business Consultant. Your job is to audit the "Knowledge Base" of a startup to see if we have enough info to build a perfect marketing strategy and survey.
            
            Current Knowledge Base:
            "${contextText.substring(0, 10000)}"
            
            Uploaded Files: ${fileNames.join(', ')}

            **Goal:** Determine what is MISSING.
            
            **Dimensions to Check (Exact or inferred):**
            1. **Value Proposition:** (Look for: "Value Prop", "USP", "Why us", or descriptions of benefits).
            2. **Target Audience:** (Look for: "Audience", "Persona", "Target", or specific demographics).
            3. **Pricing/Business Model:** (Look for: "Model", "Pricing", "Revenue", "SaaS", "Freemium").
            4. **Competitors:** (Look for: "Competitors", "Alternatives", or list of companies).
            5. **Goals:** (Look for: "Goals", "Objectives", "KPIs", "Aim").

            **Evaluation Rules:**
            - **CHECKLIST APPROACH:** Even if the description is short, if the *concept* is present, it is PASSED.
            - Specifically check for the standard headers generated by Geniy (e.g. "Value Proposition:", "Competitors:"). If these headers exist and have content, they are DEFINITELY PRESENT.
            
            **Scoring Logic (The "Geniy Assessment"):**
            - Provide a **"Strategic Readiness Score" (0-100)**.
            - Approach this as a co-founder: "How solid/prepared is this context for generating high-quality insights?"
            - **Rule of Thumb:**
                - 90-100: Comprehensive. I have everything I need to win.
                - 70-89: Good, but missing some specific details (maybe pricing or specific goals).
                - 50-69: Okay, but I'm flying blind on key areas like Competitors.
                - < 50: Too vague. I can't give good advice yet.
            - **CRITICAL:** The score MUST correlate with the specific missing dimensions you list. If "Competitors" and "Pricing" are missing, it represents a major gap in intelligence, so score accordingly.

            Output JSON Schema:
            {
                "completenessScore": number, // 0-100 (Expert Judgment)
                "missingDimensions": ["string"], // e.g. ["Pricing", "Competitors"]
                "recommendations": ["string"], // Specific behaviors to fix the missing items.
                "summary": "string" // e.g. "I think we're 70% there. If you give me the Competitors, I can give you much better results."
            }
        `;

        try {
            const result = await openRouter.complete(prompt, "openai/gpt-4o-mini", true, 1500);
            return genesis.safeParse(result);
        } catch (error) {
            console.error("Gap Analysis Failed:", error);
            return {
                completenessScore: 50,
                missingDimensions: ["Error analyzing context"],
                recommendations: ["Try uploading more documents."],
                summary: "Could not analyze context at this time."
            };
        }
    }
}

module.exports = new GapAgent();
